platform :ios, "10.0"

use_frameworks! :linkage => :static

target "BusMock" do
  pod "NBus/BusHandlers", :path => "../"
  pod "NBus/SDKHandlers", :path => "../"

  pod "NBusQQSDK"
  pod "NBusWechatSDK"
  pod "NBusWeiboSDK"

  pod "PinLayout"
  pod "RxCocoa"
  pod "SwiftTrace"
  pod "WoodPeckeriOS"
end

target "BusMockQQSDK" do
  pod "NBusQQSDK"
end

target "BusMockWechatSDK" do
  pod "NBusWechatSDK"
end

target "BusMockWeiboSDK" do
  pod "NBusWeiboSDK"
end

target "BusMockTestSDK" do
  pod "WoodPeckeriOS"
end

target "BusTests" do
  pod "NBus/BusHandlers", :path => "../"
  pod "NBus/SDKHandlers", :path => "../"

  pod "NBusQQSDK"
  pod "NBusWechatSDK"
  pod "NBusWeiboSDK"

  pod "RxCocoa"
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "nuomi1"
end
