platform :ios, "10.0"

use_frameworks! :linkage => :static

target "BusMock" do
  pod "NBus/BusHandlers", :path => "../"
  pod "NBus/SDKHandlers", :path => "../"

  pod "NBusQQSDK", :path => "../"
  pod "NBusWechatSDK", :path => "../"
  pod "NBusWeiboSDK", :path => "../"

  pod "PinLayout"
  pod "RxCocoa"
  pod "SwiftTrace"
  pod "WoodPeckeriOS"
end

target "BusMockQQSDK" do
  pod "NBusQQSDK", :path => "../"
end

target "BusMockWechatSDK" do
  pod "NBusWechatSDK", :path => "../"
end

target "BusMockWeiboSDK" do
  pod "NBusWeiboSDK", :path => "../"
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "nuomi1"
end
