platform :ios, "10.0"

use_frameworks! :linkage => :static

target "BusMock" do
  pod "NBus", :path => "../"

  pod "PinLayout"
  pod "RxCocoa"
  pod "SwiftTrace"
  pod "WoodPeckeriOS"
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "nuomi1"
end
