name: NBus

attributes:
  ORGANIZATIONNAME: nuomi1

configFiles:
  Debug: NBus/Config.xcconfig
  Release: NBus/Config.xcconfig

targetTemplates:
  BusTemplate:
    platform: iOS
    deploymentTarget: 10.0
    settings:
      base:
        SWIFT_VERSION: 5.0
    scheme: {}
  BusMockTemplate:
    templates:
      - BusTemplate
    type: application
    sources:
      - path: NBus
        excludes:
          - Model
          - View
          - AppDelegate.swift
          - AppDelegateSDK.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: $(SRCROOT)/$(PROJECT_NAME)/BusMock.entitlements
        OTHER_SWIFT_FLAGS:
          - "$(inherited)"
          - "-D ${target_name}"
  BusMockSDKTemplate:
    templates:
      - BusMockTemplate
    sources:
      - NBus/AppDelegateSDK.swift

packages:
  Logging:
    url: https://github.com/apple/swift-log
    majorVersion: 1.4.0

targets:
  BusMock:
    templates:
      - BusMockTemplate
    sources:
      - path: NBus
        includes:
          - Model
          - View
          - AppDelegate.swift
    dependencies:
      - package: Logging
  BusMockQQSDK:
    templates:
      - BusMockSDKTemplate
  BusMockWechatSDK:
    templates:
      - BusMockSDKTemplate
  BusMockWeiboSDK:
    templates:
      - BusMockSDKTemplate
  BusMockTestSDK:
    templates:
      - BusMockSDKTemplate
    sources:
      - path: NBus
        includes:
          - Model/AppState.swift
          - Model/AppState+ClearStorage.swift
          - Model/AppState+Notification.swift
    postBuildScripts:
      - script: |
          find "${PROJECT_DIR}" -name "WeiboSDK.bundle" -exec cp -R "{}" "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/" \;
    scheme:
      testTargets:
        - BusTests
  BusTests:
    templates:
      - BusTemplate
    type: bundle.unit-test
    sources:
      - path: ../Tests/NBusTests
      - path: NBus/Model
        excludes:
          - AppState+Setup.swift
    dependencies:
      - target: BusMockTestSDK
      - package: Logging
