name: NBus

attributes:
  ORGANIZATIONNAME: nuomi1

configFiles:
  Debug: NBus/Config.xcconfig
  Release: NBus/Config.xcconfig

targets:
  BusMock:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
      - path: NBus
        excludes:
          - AppDelegateQQSDK.swift
          - AppDelegateWechatSDK.swift
          - AppDelegateWeiboSDK.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ${SRCROOT}/$(PROJECT_NAME)/$(TARGET_NAME).entitlements
        SWIFT_VERSION: 5.0
    dependencies:
      - package: Logging
    scheme: {}
  BusMockQQSDK:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
      - path: NBus
        excludes:
          - Model
          - View
          - AppDelegate.swift
          - AppDelegateWechatSDK.swift
          - AppDelegateWeiboSDK.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ${SRCROOT}/$(PROJECT_NAME)/BusMock.entitlements
        SWIFT_VERSION: 5.0
    scheme: {}
  BusMockWechatSDK:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
      - path: NBus
        excludes:
          - Model
          - View
          - AppDelegate.swift
          - AppDelegateQQSDK.swift
          - AppDelegateWeiboSDK.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ${SRCROOT}/$(PROJECT_NAME)/BusMock.entitlements
        SWIFT_VERSION: 5.0
    scheme: {}
  BusMockWeiboSDK:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
      - path: NBus
        excludes:
          - Model
          - View
          - AppDelegate.swift
          - AppDelegateQQSDK.swift
          - AppDelegateWechatSDK.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ${SRCROOT}/$(PROJECT_NAME)/BusMock.entitlements
        SWIFT_VERSION: 5.0
    scheme: {}

packages:
  Logging:
    url: https://github.com/apple/swift-log
    majorVersion: 1.4.0
