name: NBus

attributes:
  ORGANIZATIONNAME: nuomi1

configFiles:
  Debug: NBus/Config.xcconfig
  Release: NBus/Config.xcconfig

targetTemplates:
  BusMockTemplate:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
      - path: NBus
        excludes:
          - Model
          - View
          - AppDelegate.swift
          - AppDelegateSDK.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: $(SRCROOT)/$(PROJECT_NAME)/BusMock.entitlements
        OTHER_SWIFT_FLAGS:
          - "$(inherited)"
          - "-D ${target_name}"
        SWIFT_VERSION: 5.0
    scheme: {}

packages:
  Logging:
    url: https://github.com/apple/swift-log
    majorVersion: 1.4.0

targets:
  BusMock:
    templates:
      - BusMockTemplate
    sources:
      - path: NBus
        includes:
          - Model
          - View
          - AppDelegate.swift
    dependencies:
      - package: Logging
  BusMockQQSDK:
    templates:
      - BusMockTemplate
    sources:
      - NBus/AppDelegateSDK.swift
  BusMockWechatSDK:
    templates:
      - BusMockTemplate
    sources:
      - NBus/AppDelegateSDK.swift
  BusMockWeiboSDK:
    templates:
      - BusMockTemplate
    sources:
      - NBus/AppDelegateSDK.swift
