disabled_rules:
  - nesting
  - trailing_comma

excluded:
  - Example/Carthage
  - Example/Pods

identifier_name:
  excluded:
    - qq

included:
  - Example
  - NBus
  - Tests
  - Package.swift

line_length:
  ignores_comments: true
  ignores_interpolated_strings: true

type_name:
  excluded:
    - QQ
