# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :setup_xcodegen do
    xcodegen
  end

  lane :setup_cocoapods do
    cocoapods
  end

  lane :setup do
    setup_xcodegen
    setup_cocoapods
  end

  lane :format do
    swiftformat
  end

  lane :lint do
    swiftlint
  end
end
