name: Swift

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer

jobs:
  setup:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Xcode
        run: bundle exec fastlane setup
  swift-lint:
    needs: setup
    runs-on: macos-10.15
    steps:
      - name: SwiftLint
        run: bundle exec fastlane lint
  pod-lint:
    needs: setup
    runs-on: macos-10.15
    strategy:
      matrix:
        target:
          - NBusQQSDK
          - NBusWechatSDK
          - NBusWeiboSDK
          - NBus
          - NBusBusHandlers
          - NBusSDKHandlers
    steps:
      - name: CocoaPods Lint
        run: bundle exec fastlane pod_lint target:${{ matrix.target }}
